server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practice
    username: root
    password: dlsdlwkd12.
    
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
    properties:
      hibernate:
        diarect: org.hibernate.dialect.H2Dialect
        show_sql: true 
        format_sql: true 
        use_sql_comments: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB